---
- name: Disable older swap file
  shell: "swapoff {{ swapfile_base_dir }}/{{ swapfile_cur_id }}"

- name: Remove older swap file from /etc/fstab
  mount:
    src:    "{{ swapfile_base_dir }}/{{ swapfile_cur_id }}"
    name:   "swap{{ swapfile_cur_id }}"
    fstype: "swap"
    state:  "absent"

- name: Remove older swap file
  file:
    path: "{{ swapfile_base_dir }}/{{ swapfile_cur_id }}"
    state: "absent"
